/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AgeGroup = IDL.Variant({
  'adult18_30' : IDL.Null,
  'senior31plus' : IDL.Null,
  'under12' : IDL.Null,
  'teen13_17' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'ageGroup' : AgeGroup,
});
export const Time = IDL.Int;
export const QuizScore = IDL.Record({
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'timestamp' : Time,
  'playerName' : IDL.Text,
});
export const TrainingLog = IDL.Record({
  'section' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignAdminRole' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignUserRole' : IDL.Func([IDL.Principal], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTopScores' : IDL.Func([IDL.Principal], [IDL.Vec(QuizScore)], ['query']),
  'getTrainingLogs' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(TrainingLog)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logTrainingSession' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitQuizScore' : IDL.Func([QuizScore], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AgeGroup = IDL.Variant({
    'adult18_30' : IDL.Null,
    'senior31plus' : IDL.Null,
    'under12' : IDL.Null,
    'teen13_17' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'ageGroup' : AgeGroup });
  const Time = IDL.Int;
  const QuizScore = IDL.Record({
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'timestamp' : Time,
    'playerName' : IDL.Text,
  });
  const TrainingLog = IDL.Record({ 'section' : IDL.Text, 'timestamp' : Time });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignAdminRole' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignUserRole' : IDL.Func([IDL.Principal], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTopScores' : IDL.Func([IDL.Principal], [IDL.Vec(QuizScore)], ['query']),
    'getTrainingLogs' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(TrainingLog)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logTrainingSession' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitQuizScore' : IDL.Func([QuizScore], [], []),
  });
};

export const init = ({ IDL }) => { return []; };