/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AssessmentAnswers = IDL.Record({
  'item10' : IDL.Nat,
  'item11' : IDL.Nat,
  'item12' : IDL.Nat,
  'item13' : IDL.Nat,
  'item14' : IDL.Nat,
  'item15' : IDL.Nat,
  'item16' : IDL.Nat,
  'item17' : IDL.Nat,
  'item18' : IDL.Nat,
  'item19' : IDL.Nat,
  'item20' : IDL.Nat,
  'item21' : IDL.Nat,
  'item22' : IDL.Nat,
  'item23' : IDL.Nat,
  'item24' : IDL.Nat,
  'item25' : IDL.Nat,
  'item26' : IDL.Nat,
  'item27' : IDL.Nat,
  'item28' : IDL.Nat,
  'item29' : IDL.Nat,
  'item30' : IDL.Nat,
  'item31' : IDL.Nat,
  'item32' : IDL.Nat,
  'item33' : IDL.Nat,
  'item34' : IDL.Nat,
  'item35' : IDL.Nat,
  'item36' : IDL.Nat,
  'item37' : IDL.Nat,
  'item38' : IDL.Nat,
  'item39' : IDL.Nat,
  'item40' : IDL.Nat,
  'item41' : IDL.Nat,
  'item42' : IDL.Nat,
  'item43' : IDL.Nat,
  'item44' : IDL.Nat,
  'item45' : IDL.Nat,
  'item46' : IDL.Nat,
  'item47' : IDL.Nat,
  'item48' : IDL.Nat,
  'item49' : IDL.Nat,
  'item50' : IDL.Nat,
  'item1' : IDL.Nat,
  'item2' : IDL.Nat,
  'item3' : IDL.Nat,
  'item4' : IDL.Nat,
  'item5' : IDL.Nat,
  'item6' : IDL.Nat,
  'item7' : IDL.Nat,
  'item8' : IDL.Nat,
  'item9' : IDL.Nat,
});
export const InterpretationCategory = IDL.Variant({
  'good' : IDL.Null,
  'indicatesDevelopment' : IDL.Null,
});
export const SingleCompetencyScore = IDL.Record({
  'total' : IDL.Nat,
  'category' : InterpretationCategory,
});
export const AssessmentResults = IDL.Record({
  'selfAwareness' : SingleCompetencyScore,
  'socialSkill' : SingleCompetencyScore,
  'managingEmotions' : SingleCompetencyScore,
  'motivatingOneself' : SingleCompetencyScore,
  'empathy' : SingleCompetencyScore,
});
export const Time = IDL.Int;
export const Submission = IDL.Record({
  'answers' : AssessmentAnswers,
  'results' : AssessmentResults,
  'timestamp' : Time,
  'respondent' : IDL.Principal,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignSurveyorAccess' : IDL.Func([IDL.Principal], [], []),
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompetencyMapping' : IDL.Func([], [IDL.Text], ['query']),
  'getMySubmission' : IDL.Func([], [IDL.Opt(Submission)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'revokeSurveyorAccess' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitAssessment' : IDL.Func([AssessmentAnswers], [AssessmentResults], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AssessmentAnswers = IDL.Record({
    'item10' : IDL.Nat,
    'item11' : IDL.Nat,
    'item12' : IDL.Nat,
    'item13' : IDL.Nat,
    'item14' : IDL.Nat,
    'item15' : IDL.Nat,
    'item16' : IDL.Nat,
    'item17' : IDL.Nat,
    'item18' : IDL.Nat,
    'item19' : IDL.Nat,
    'item20' : IDL.Nat,
    'item21' : IDL.Nat,
    'item22' : IDL.Nat,
    'item23' : IDL.Nat,
    'item24' : IDL.Nat,
    'item25' : IDL.Nat,
    'item26' : IDL.Nat,
    'item27' : IDL.Nat,
    'item28' : IDL.Nat,
    'item29' : IDL.Nat,
    'item30' : IDL.Nat,
    'item31' : IDL.Nat,
    'item32' : IDL.Nat,
    'item33' : IDL.Nat,
    'item34' : IDL.Nat,
    'item35' : IDL.Nat,
    'item36' : IDL.Nat,
    'item37' : IDL.Nat,
    'item38' : IDL.Nat,
    'item39' : IDL.Nat,
    'item40' : IDL.Nat,
    'item41' : IDL.Nat,
    'item42' : IDL.Nat,
    'item43' : IDL.Nat,
    'item44' : IDL.Nat,
    'item45' : IDL.Nat,
    'item46' : IDL.Nat,
    'item47' : IDL.Nat,
    'item48' : IDL.Nat,
    'item49' : IDL.Nat,
    'item50' : IDL.Nat,
    'item1' : IDL.Nat,
    'item2' : IDL.Nat,
    'item3' : IDL.Nat,
    'item4' : IDL.Nat,
    'item5' : IDL.Nat,
    'item6' : IDL.Nat,
    'item7' : IDL.Nat,
    'item8' : IDL.Nat,
    'item9' : IDL.Nat,
  });
  const InterpretationCategory = IDL.Variant({
    'good' : IDL.Null,
    'indicatesDevelopment' : IDL.Null,
  });
  const SingleCompetencyScore = IDL.Record({
    'total' : IDL.Nat,
    'category' : InterpretationCategory,
  });
  const AssessmentResults = IDL.Record({
    'selfAwareness' : SingleCompetencyScore,
    'socialSkill' : SingleCompetencyScore,
    'managingEmotions' : SingleCompetencyScore,
    'motivatingOneself' : SingleCompetencyScore,
    'empathy' : SingleCompetencyScore,
  });
  const Time = IDL.Int;
  const Submission = IDL.Record({
    'answers' : AssessmentAnswers,
    'results' : AssessmentResults,
    'timestamp' : Time,
    'respondent' : IDL.Principal,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignSurveyorAccess' : IDL.Func([IDL.Principal], [], []),
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompetencyMapping' : IDL.Func([], [IDL.Text], ['query']),
    'getMySubmission' : IDL.Func([], [IDL.Opt(Submission)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'revokeSurveyorAccess' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitAssessment' : IDL.Func([AssessmentAnswers], [AssessmentResults], []),
  });
};

export const init = ({ IDL }) => { return []; };