import type { TriviaQuestion } from "../lib/trivia/openTrivia";

export const fifaQuizQuestions: TriviaQuestion[] = [
  {
    question: "Which country won the first FIFA World Cup in 1930?",
    correctAnswer: "Uruguay",
    answers: ["Uruguay", "Brazil", "Argentina", "Italy"],
    category: "FIFA World Cup",
    difficulty: "medium",
  },
  {
    question:
      "In which year was FIFA (Fédération Internationale de Football Association) founded?",
    correctAnswer: "1904",
    answers: ["1904", "1900", "1920", "1895"],
    category: "FIFA History",
    difficulty: "hard",
  },
  {
    question: "Which player has won the most FIFA World Cup titles?",
    correctAnswer: "Pelé",
    answers: ["Pelé", "Diego Maradona", "Lionel Messi", "Cristiano Ronaldo"],
    category: "FIFA World Cup",
    difficulty: "easy",
  },
  {
    question:
      "What is the maximum overall rating a player can achieve in FIFA video games?",
    correctAnswer: "99",
    answers: ["99", "100", "95", "98"],
    category: "FIFA Video Game",
    difficulty: "easy",
  },
  {
    question: "Which country hosted the 2014 FIFA World Cup?",
    correctAnswer: "Brazil",
    answers: ["Brazil", "South Africa", "Russia", "Germany"],
    category: "FIFA World Cup",
    difficulty: "easy",
  },
  {
    question: "Who is the all-time top scorer in FIFA World Cup history?",
    correctAnswer: "Miroslav Klose",
    answers: ["Miroslav Klose", "Ronaldo", "Pelé", "Gerd Müller"],
    category: "FIFA World Cup",
    difficulty: "medium",
  },
  {
    question: "Which FIFA game introduced the Ultimate Team mode?",
    correctAnswer: "FIFA 09",
    answers: ["FIFA 09", "FIFA 10", "FIFA 08", "FIFA 11"],
    category: "FIFA Video Game",
    difficulty: "hard",
  },
  {
    question: "How many teams participate in the FIFA World Cup finals?",
    correctAnswer: "32",
    answers: ["32", "24", "48", "16"],
    category: "FIFA World Cup",
    difficulty: "medium",
  },
  {
    question: "Which country has won the most FIFA World Cup titles?",
    correctAnswer: "Brazil",
    answers: ["Brazil", "Germany", "Italy", "Argentina"],
    category: "FIFA World Cup",
    difficulty: "easy",
  },
  {
    question: "What does FIFA stand for in English?",
    correctAnswer: "International Federation of Association Football",
    answers: [
      "International Federation of Association Football",
      "Federation of International Football Associations",
      "Football International Federation Association",
      "Federation International Football Association",
    ],
    category: "FIFA History",
    difficulty: "medium",
  },
  {
    question: "Which player won the FIFA Ballon d'Or in 2018?",
    correctAnswer: "Luka Modrić",
    answers: [
      "Luka Modrić",
      "Cristiano Ronaldo",
      "Lionel Messi",
      "Kylian Mbappé",
    ],
    category: "FIFA Awards",
    difficulty: "medium",
  },
  {
    question: "In which city is FIFA headquarters located?",
    correctAnswer: "Zürich",
    answers: ["Zürich", "Geneva", "Paris", "London"],
    category: "FIFA History",
    difficulty: "medium",
  },
  {
    question: "Which country won the 2018 FIFA World Cup?",
    correctAnswer: "France",
    answers: ["France", "Croatia", "Belgium", "England"],
    category: "FIFA World Cup",
    difficulty: "easy",
  },
  {
    question: "What is the name of the FIFA World Cup trophy?",
    correctAnswer: "FIFA World Cup Trophy",
    answers: [
      "FIFA World Cup Trophy",
      "Jules Rimet Trophy",
      "Golden Globe",
      "Victory Cup",
    ],
    category: "FIFA World Cup",
    difficulty: "easy",
  },
  {
    question: "Which FIFA game first featured women's national teams?",
    correctAnswer: "FIFA 16",
    answers: ["FIFA 16", "FIFA 17", "FIFA 15", "FIFA 18"],
    category: "FIFA Video Game",
    difficulty: "medium",
  },
  {
    question: "How often is the FIFA World Cup held?",
    correctAnswer: "Every 4 years",
    answers: ["Every 4 years", "Every 2 years", "Every 3 years", "Annually"],
    category: "FIFA World Cup",
    difficulty: "easy",
  },
  {
    question: "Which player has appeared on the most FIFA video game covers?",
    correctAnswer: "Lionel Messi",
    answers: [
      "Lionel Messi",
      "Cristiano Ronaldo",
      "Wayne Rooney",
      "Kylian Mbappé",
    ],
    category: "FIFA Video Game",
    difficulty: "medium",
  },
  {
    question:
      "What was the first FIFA World Cup held outside of Europe and South America?",
    correctAnswer: "1994 USA",
    answers: [
      "1994 USA",
      "2002 South Korea/Japan",
      "1986 Mexico",
      "2010 South Africa",
    ],
    category: "FIFA World Cup",
    difficulty: "hard",
  },
  {
    question: "Which country won the first FIFA Women's World Cup in 1991?",
    correctAnswer: "United States",
    answers: ["United States", "Norway", "Germany", "Sweden"],
    category: "FIFA World Cup",
    difficulty: "medium",
  },
  {
    question: "What is the name of FIFA's official anthem?",
    correctAnswer: "FIFA Anthem",
    answers: [
      "FIFA Anthem",
      "World Cup Theme",
      "Football Forever",
      "The Beautiful Game",
    ],
    category: "FIFA History",
    difficulty: "hard",
  },
  {
    question: "Which FIFA game introduced the Journey story mode?",
    correctAnswer: "FIFA 17",
    answers: ["FIFA 17", "FIFA 18", "FIFA 16", "FIFA 19"],
    category: "FIFA Video Game",
    difficulty: "medium",
  },
  {
    question: 'Who scored the "Hand of God" goal in the 1986 FIFA World Cup?',
    correctAnswer: "Diego Maradona",
    answers: ["Diego Maradona", "Pelé", "Gary Lineker", "Michel Platini"],
    category: "FIFA World Cup",
    difficulty: "easy",
  },
  {
    question: "Which country will host the 2026 FIFA World Cup?",
    correctAnswer: "USA, Canada, and Mexico",
    answers: ["USA, Canada, and Mexico", "Qatar", "Russia", "Brazil"],
    category: "FIFA World Cup",
    difficulty: "medium",
  },
  {
    question:
      "What is the maximum number of substitutions allowed in a FIFA World Cup match (as of 2022)?",
    correctAnswer: "5",
    answers: ["5", "3", "7", "4"],
    category: "FIFA Rules",
    difficulty: "medium",
  },
  {
    question: "Which player won the Golden Boot at the 2022 FIFA World Cup?",
    correctAnswer: "Kylian Mbappé",
    answers: [
      "Kylian Mbappé",
      "Lionel Messi",
      "Julián Álvarez",
      "Olivier Giroud",
    ],
    category: "FIFA World Cup",
    difficulty: "medium",
  },
  {
    question:
      "In FIFA Ultimate Team, what color represents the highest rated special cards?",
    correctAnswer: "Black (TOTY/TOTS)",
    answers: ["Black (TOTY/TOTS)", "Gold", "Red", "Blue"],
    category: "FIFA Video Game",
    difficulty: "medium",
  },
  {
    question:
      "Which country hosted the 2010 FIFA World Cup, the first in Africa?",
    correctAnswer: "South Africa",
    answers: ["South Africa", "Egypt", "Nigeria", "Morocco"],
    category: "FIFA World Cup",
    difficulty: "easy",
  },
  {
    question: "Who is the current FIFA President (as of 2024)?",
    correctAnswer: "Gianni Infantino",
    answers: [
      "Gianni Infantino",
      "Sepp Blatter",
      "Michel Platini",
      "João Havelange",
    ],
    category: "FIFA History",
    difficulty: "medium",
  },
  {
    question: "Which FIFA game was the first to use the Frostbite engine?",
    correctAnswer: "FIFA 17",
    answers: ["FIFA 17", "FIFA 18", "FIFA 16", "FIFA 19"],
    category: "FIFA Video Game",
    difficulty: "hard",
  },
  {
    question:
      "What is the official ball used in the 2022 FIFA World Cup called?",
    correctAnswer: "Al Rihla",
    answers: ["Al Rihla", "Telstar", "Jabulani", "Brazuca"],
    category: "FIFA World Cup",
    difficulty: "hard",
  },
  {
    question: "Which country won the 2022 FIFA World Cup?",
    correctAnswer: "Argentina",
    answers: ["Argentina", "France", "Croatia", "Morocco"],
    category: "FIFA World Cup",
    difficulty: "easy",
  },
  {
    question: "How many FIFA confederations are there?",
    correctAnswer: "6",
    answers: ["6", "5", "7", "8"],
    category: "FIFA History",
    difficulty: "hard",
  },
  {
    question: "Which player has won the most FIFA Ballon d'Or awards?",
    correctAnswer: "Lionel Messi",
    answers: [
      "Lionel Messi",
      "Cristiano Ronaldo",
      "Michel Platini",
      "Johan Cruyff",
    ],
    category: "FIFA Awards",
    difficulty: "easy",
  },
  {
    question: "What is the name of the FIFA Club World Cup trophy?",
    correctAnswer: "FIFA Club World Cup Trophy",
    answers: [
      "FIFA Club World Cup Trophy",
      "Intercontinental Cup",
      "Champions Trophy",
      "World Club Trophy",
    ],
    category: "FIFA Tournaments",
    difficulty: "medium",
  },
  {
    question: "Which FIFA game introduced HyperMotion technology?",
    correctAnswer: "FIFA 22",
    answers: ["FIFA 22", "FIFA 23", "FIFA 21", "FIFA 20"],
    category: "FIFA Video Game",
    difficulty: "medium",
  },
  {
    question:
      "In which year did the FIFA World Cup expand from 24 to 32 teams?",
    correctAnswer: "1998",
    answers: ["1998", "1994", "2002", "1990"],
    category: "FIFA World Cup",
    difficulty: "hard",
  },
  {
    question: "Which country has hosted the FIFA World Cup the most times?",
    correctAnswer: "Mexico",
    answers: ["Mexico", "Brazil", "Italy", "Germany"],
    category: "FIFA World Cup",
    difficulty: "hard",
  },
  {
    question: "What is the fastest goal scored in FIFA World Cup history?",
    correctAnswer: "11 seconds",
    answers: ["11 seconds", "15 seconds", "8 seconds", "20 seconds"],
    category: "FIFA World Cup",
    difficulty: "hard",
  },
  {
    question: "Which FIFA game was rebranded to EA Sports FC?",
    correctAnswer: "FIFA 24 became EA Sports FC 24",
    answers: [
      "FIFA 24 became EA Sports FC 24",
      "FIFA 23",
      "FIFA 25",
      "FIFA 22",
    ],
    category: "FIFA Video Game",
    difficulty: "medium",
  },
  {
    question: "Who won the FIFA World Cup Golden Ball in 2022?",
    correctAnswer: "Lionel Messi",
    answers: [
      "Lionel Messi",
      "Kylian Mbappé",
      "Luka Modrić",
      "Emiliano Martínez",
    ],
    category: "FIFA World Cup",
    difficulty: "easy",
  },
  {
    question: "Which country won the first FIFA Confederations Cup in 1992?",
    correctAnswer: "Argentina",
    answers: ["Argentina", "Brazil", "Mexico", "Saudi Arabia"],
    category: "FIFA Tournaments",
    difficulty: "hard",
  },
  {
    question: "What is the name of the FIFA Fair Play Trophy?",
    correctAnswer: "FIFA Fair Play Trophy",
    answers: [
      "FIFA Fair Play Trophy",
      "Spirit of the Game Award",
      "Sportsmanship Cup",
      "Fair Play Award",
    ],
    category: "FIFA Awards",
    difficulty: "medium",
  },
  {
    question:
      "Which player scored the winning goal in the 2014 FIFA World Cup final?",
    correctAnswer: "Mario Götze",
    answers: ["Mario Götze", "Thomas Müller", "Lionel Messi", "Miroslav Klose"],
    category: "FIFA World Cup",
    difficulty: "medium",
  },
  {
    question: 'In FIFA Ultimate Team, what does "TOTW" stand for?',
    correctAnswer: "Team of the Week",
    answers: [
      "Team of the Week",
      "Top of the World",
      "Tournament of the Week",
      "Team of the Winners",
    ],
    category: "FIFA Video Game",
    difficulty: "easy",
  },
  {
    question:
      "Which country hosted the 2002 FIFA World Cup alongside South Korea?",
    correctAnswer: "Japan",
    answers: ["Japan", "China", "Australia", "Thailand"],
    category: "FIFA World Cup",
    difficulty: "easy",
  },
  {
    question: "What is the official FIFA world ranking system called?",
    correctAnswer: "FIFA World Ranking",
    answers: [
      "FIFA World Ranking",
      "FIFA Power Index",
      "FIFA Global Rating",
      "FIFA Team Score",
    ],
    category: "FIFA History",
    difficulty: "easy",
  },
  {
    question:
      "Which player won the FIFA Puskás Award for the best goal in 2020?",
    correctAnswer: "Son Heung-min",
    answers: [
      "Son Heung-min",
      "Cristiano Ronaldo",
      "Lionel Messi",
      "Luis Suárez",
    ],
    category: "FIFA Awards",
    difficulty: "hard",
  },
  {
    question:
      "How many minutes of extra time are played in a FIFA World Cup knockout match if tied?",
    correctAnswer: "30 minutes",
    answers: ["30 minutes", "20 minutes", "15 minutes", "40 minutes"],
    category: "FIFA Rules",
    difficulty: "medium",
  },
  {
    question: "Which FIFA game introduced Volta Football mode?",
    correctAnswer: "FIFA 20",
    answers: ["FIFA 20", "FIFA 21", "FIFA 19", "FIFA 22"],
    category: "FIFA Video Game",
    difficulty: "medium",
  },
  {
    question:
      "What is the youngest age a player can be to participate in the FIFA World Cup?",
    correctAnswer: "No minimum age",
    answers: ["No minimum age", "16 years", "18 years", "15 years"],
    category: "FIFA Rules",
    difficulty: "hard",
  },
];
