/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface SingleCompetencyScore {
    total: bigint;
    category: InterpretationCategory;
}
export interface AssessmentAnswers {
    item10: bigint;
    item11: bigint;
    item12: bigint;
    item13: bigint;
    item14: bigint;
    item15: bigint;
    item16: bigint;
    item17: bigint;
    item18: bigint;
    item19: bigint;
    item20: bigint;
    item21: bigint;
    item22: bigint;
    item23: bigint;
    item24: bigint;
    item25: bigint;
    item26: bigint;
    item27: bigint;
    item28: bigint;
    item29: bigint;
    item30: bigint;
    item31: bigint;
    item32: bigint;
    item33: bigint;
    item34: bigint;
    item35: bigint;
    item36: bigint;
    item37: bigint;
    item38: bigint;
    item39: bigint;
    item40: bigint;
    item41: bigint;
    item42: bigint;
    item43: bigint;
    item44: bigint;
    item45: bigint;
    item46: bigint;
    item47: bigint;
    item48: bigint;
    item49: bigint;
    item50: bigint;
    item1: bigint;
    item2: bigint;
    item3: bigint;
    item4: bigint;
    item5: bigint;
    item6: bigint;
    item7: bigint;
    item8: bigint;
    item9: bigint;
}
export interface AssessmentResults {
    selfAwareness: SingleCompetencyScore;
    socialSkill: SingleCompetencyScore;
    managingEmotions: SingleCompetencyScore;
    motivatingOneself: SingleCompetencyScore;
    empathy: SingleCompetencyScore;
}
export interface Submission {
    answers: AssessmentAnswers;
    results: AssessmentResults;
    timestamp: Time;
    respondent: Principal;
}
export interface UserProfile {
    name: string;
}
export enum InterpretationCategory {
    good = "good",
    indicatesDevelopment = "indicatesDevelopment"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignSurveyorAccess(user: Principal): Promise<void>;
    getAllSubmissions(): Promise<Array<Submission>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCompetencyMapping(): Promise<string>;
    getMySubmission(): Promise<Submission | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    revokeSurveyorAccess(user: Principal): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitAssessment(answers: AssessmentAnswers): Promise<AssessmentResults>;
}
import type { AssessmentAnswers as _AssessmentAnswers, AssessmentResults as _AssessmentResults, InterpretationCategory as _InterpretationCategory, SingleCompetencyScore as _SingleCompetencyScore, Submission as _Submission, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignSurveyorAccess(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignSurveyorAccess(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignSurveyorAccess(arg0);
            return result;
        }
    }
    async getAllSubmissions(): Promise<Array<Submission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSubmissions();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSubmissions();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompetencyMapping(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompetencyMapping();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompetencyMapping();
            return result;
        }
    }
    async getMySubmission(): Promise<Submission | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySubmission();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySubmission();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async revokeSurveyorAccess(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeSurveyorAccess(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeSurveyorAccess(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitAssessment(arg0: AssessmentAnswers): Promise<AssessmentResults> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAssessment(arg0);
                return from_candid_AssessmentResults_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAssessment(arg0);
            return from_candid_AssessmentResults_n6(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AssessmentResults_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssessmentResults): AssessmentResults {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_InterpretationCategory_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InterpretationCategory): InterpretationCategory {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_SingleCompetencyScore_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SingleCompetencyScore): SingleCompetencyScore {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Submission_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Submission): Submission {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Submission]): Submission | null {
    return value.length === 0 ? null : from_candid_Submission_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    answers: _AssessmentAnswers;
    results: _AssessmentResults;
    timestamp: _Time;
    respondent: Principal;
}): {
    answers: AssessmentAnswers;
    results: AssessmentResults;
    timestamp: Time;
    respondent: Principal;
} {
    return {
        answers: value.answers,
        results: from_candid_AssessmentResults_n6(_uploadFile, _downloadFile, value.results),
        timestamp: value.timestamp,
        respondent: value.respondent
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    selfAwareness: _SingleCompetencyScore;
    socialSkill: _SingleCompetencyScore;
    managingEmotions: _SingleCompetencyScore;
    motivatingOneself: _SingleCompetencyScore;
    empathy: _SingleCompetencyScore;
}): {
    selfAwareness: SingleCompetencyScore;
    socialSkill: SingleCompetencyScore;
    managingEmotions: SingleCompetencyScore;
    motivatingOneself: SingleCompetencyScore;
    empathy: SingleCompetencyScore;
} {
    return {
        selfAwareness: from_candid_SingleCompetencyScore_n8(_uploadFile, _downloadFile, value.selfAwareness),
        socialSkill: from_candid_SingleCompetencyScore_n8(_uploadFile, _downloadFile, value.socialSkill),
        managingEmotions: from_candid_SingleCompetencyScore_n8(_uploadFile, _downloadFile, value.managingEmotions),
        motivatingOneself: from_candid_SingleCompetencyScore_n8(_uploadFile, _downloadFile, value.motivatingOneself),
        empathy: from_candid_SingleCompetencyScore_n8(_uploadFile, _downloadFile, value.empathy)
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    category: _InterpretationCategory;
}): {
    total: bigint;
    category: InterpretationCategory;
} {
    return {
        total: value.total,
        category: from_candid_InterpretationCategory_n10(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    good: null;
} | {
    indicatesDevelopment: null;
}): InterpretationCategory {
    return "good" in value ? InterpretationCategory.good : "indicatesDevelopment" in value ? InterpretationCategory.indicatesDevelopment : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Submission>): Array<Submission> {
    return value.map((x)=>from_candid_Submission_n4(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
